# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: RUN@KAIST
  ko: RUN@KAIST
email: contact@kaist.run
description:
  en: KAIST Algorithmic Problem Solving Club
  ko: KAIST 알고리즘 문제 해결 동아리
index:
  en: en
  ko: ko
feed:
  en: /feed.xml
  fr: /flux.xml
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaist.run" # the base hostname & protocol for your site
twitter_username: 
github_username: RUN-KAIST

# Build settings
markdown: kramdown

plugins:
  - jekyll-redirect-from